import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";
import { GoogleTagManager } from "@next/third-parties/google";
// import { GoogleAnalytics } from "@next/third-parties/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    ><head>
      
    </head>
      <body className="min-h-full flex flex-col">
         <GoogleTagManager gtmId="GTM-ND2G96NZ" />
        <Nav />
        <main>{children}</main>
      </body>
      {/* <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}/> */}
      {/* <GoogleAnalytics gaId="G-V6FMNZT33B" /> */}
      {/* <GoogleAnalytics gaId="GTM-ND2G96NZ" /> */}
    </html>
  );
}
